services:
  api:
    platform: linux/amd64
    container_name: ecommerce
    env_file:
      - docker.env
    image: "ecommerce"
    build: .
    tty: true
    volumes:
      - .:/project
    ports:
      - 0.0.0.0:8000:8000
    command: uvicorn source.app.adapter.fastapi.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:15 # Use the desired PostgreSQL version
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432" # Map host port to container port
    environment:
      POSTGRES_USER: someone          # Set PostgreSQL username
      POSTGRES_PASSWORD: example  # Set PostgreSQL password
      POSTGRES_DB: ecommerce        # Set PostgreSQL database name
    volumes:
      - postgres-data:/var/lib/postgresql/data  

volumes:
  postgres-data: